### ISSUE TITLE
Interest in contributions?

### ISSUE THREAD

**Issue by outofcoffee** [sosedoff/cloudwatchlogs#3]
Hello, thank you very much for this excellent application!

I raised this issue to ask if you were interested in contributions.

Here are a few for which I could raise PRs, if you're interested:

* [Enables UI to be customised with command line flags](https://github.com/outofcoffee/cloudwatchlogs/commit/232732ddd9fc0b59f002d71419b19342db663d3d)
* [Migrates to Go 1.13 and Go Modules](https://github.com/outofcoffee/cloudwatchlogs/commit/85f207dee5babefeed6a5cc78cb039bef51e6c47)
* [Uses Docker entrypoint instead of command](https://github.com/outofcoffee/cloudwatchlogs/commit/bb9b07539b4205dc2fa7abcbd0159728e3bb9cd4)

**Comment by sosedoff** [comment]
yeah sure, send those as separate prs
